FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y gcc g++ make

RUN apt-get install --no-install-recommends -y build-essential libgmp3-dev
RUN apt-get install -y build-essential python3-dev python3-pip python3-setuptools python3-wheel 
RUN apt-get install -y python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
RUN apt-get install -y python3-matplotlib

RUN pip3 install WeasyPrint

WORKDIR /app

ADD requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app/src

WORKDIR /app/src

ENV FLASK_APP=app

EXPOSE 5000

CMD [ "flask", "run","--host", "0.0.0.0", "--port", "5000", "--reload"]
