FROM node:alpine3.15 as npm_builder

WORKDIR /app
COPY package.json /app

COPY .eslintrc.js /app
COPY .prettierrc.json /app
COPY vite.config.js /app
COPY public /app/public
COPY index.html /app
COPY src /app/src

RUN yarn install

RUN yarn run build

########################################

FROM nginx:1.15

COPY --from=npm_builder /app/dist /usr/share/nginx/html

RUN echo '\n\
upstream backend {\n\
    server fair-backend-service.fair.svc.cluster.local:5000;\n\
}\n\
\n\
server {\n\
\n\
    listen       8000;\n\
    server_name  0.0.0.0;\n\
\n\
    resolver 127.0.0.11 valid=10s;\n\
    root   /usr/share/nginx/html/;\n\
    index  index.html;\n\
\n\
    proxy_read_timeout 300;\n\
    proxy_connect_timeout 300;\n\
    proxy_send_timeout 300;\n\
\n\
    client_max_body_size   500M;\n\
\n\
    location / {\n\
        try_files $uri $uri/ =404;\n\
    }\n\
\n\
    location /dashboard {\n\
        return 301 /;\n\
    }\n\
\n\
    location /benchmark {\n\
        return 301 /;\n\
    }\n\
\n\
    location /about {\n\
        return 301 /;\n\
    }\n\
\n\
    location /legal {\n\
        return 301 /;\n\
    }\n\
\n\
    location /api {\n\
        proxy_pass http://backend/api;\n\
    }\n\
}\n\
' > /etc/nginx/conf.d/default.conf

########################################

#FROM node:alpine3.15

#WORKDIR /app

#COPY . /app

#RUN npm install

#EXPOSE 5173

#CMD ["npm", "run", "dev"]

