apiVersion: apps/v1
kind: Deployment
metadata:
  name: fair-backend
  namespace: fair
  labels:
    app.kubernetes.io/name: fair-backend-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fair-backend-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fair-backend-pod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: back
          image: fair-backend
          imagePullPolicy: Always
          env:
          - name: SERVER_URL
            value: "http://fair-metafair-service.fair.svc.cluster.local:80"
          - name: FOOPS_URL
            value: "http://fair-foops-service.fair.svc.cluster.local:8083"
          - name: METAFAIR_HOST
            value: "fair-metafair-service.fair.svc.cluster.local"
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@fair-db-service.fair.svc.cluster.local:5432/onto_eval"
          ports:
            - name: port5000
              containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: fair-backend-service
  namespace: fair
spec:
  selector:
    app.kubernetes.io/name: fair-backend-pod
  ports:
    - name: port5000
      protocol: TCP
      port: 5000
      targetPort: 5000
