apiVersion: apps/v1
kind: Deployment
metadata:
  name: fair-foops
  namespace: fair
  labels:
    app.kubernetes.io/name: fair-foops-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fair-foops-pod
      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fair-foops-pod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:

      - name: foops
        image: foops-service
        imagePullPolicy: Always
        ports:
          - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: fair-foops-service
  namespace: fair
spec:
  selector:
    app.kubernetes.io/name: fair-foops-pod
  type: ClusterIP
  ports:
    - name: port8083
      protocol: TCP
      port: 8083
      targetPort: 8083
