apiVersion: apps/v1
kind: Deployment
metadata:
  name: fair-db
  namespace: fair
  labels:
    app.kubernetes.io/name: fair-db-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fair-db-pod
      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fair-db-pod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:

      - name: postgres
        image: postgres:14.7
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "onto_eval"
        ports:
          - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: fair-db-service
  namespace: fair
spec:
  selector:
    app.kubernetes.io/name: fair-db-pod
  ports:
    - name: port5432
      protocol: TCP
      port: 5432
      targetPort: 5432
